### ISSUE TITLE
GKE workload identity pod with PGAdapter as sidecar can't create a table with UNIQUE,serial,timestamp

### ISSUE THREAD

**Issue by hilliao** [GoogleCloudPlatform/pgadapter#350]
I created the following deployment in GKE autopilot with GKE workload identity configured properly. I'm able to use `psql -h localhost` command to connect to the Spanner database of PosgreSQL interface, `psql-test` under instance `hil-test`. Here's the deployment file:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcloud-psql
  labels:
    app: pgadapter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadapter
  template:
    metadata:
      labels:
        app: pgadapter
    spec:
      serviceAccountName: spanner
      containers:
      - name: gcloud
        image: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
      - name: spanner-pgadapter
        image: gcr.io/cloud-spanner-pg-adapter/pgadapter:latest
        args: [ "-p PROJECT_ID -i hil-test -d psql-test -x" ]
```
However, I found the PostgreSQL create table syntax compatibility is quite limited. I want to confirm that's indeed the case. I tried an example from the Internet to create a table with the following DDL:

```sh
psql-test=> CREATE TABLE accounts (
 user_id serial PRIMARY KEY,
 username VARCHAR ( 50 ) UNIQUE NOT NULL,
 password VARCHAR ( 50 ) NOT NULL,
 email VARCHAR ( 255 ) UNIQUE NOT NULL,
 created_on TIMESTAMP NOT NULL,
        last_login TIMESTAMP 
);
ERROR:  INVALID_ARGUMENT: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Type <serial> is not supported.
psql-test=> CREATE TABLE accounts (
 user_id bigint PRIMARY KEY,
 username VARCHAR ( 50 ) UNIQUE NOT NULL,
 password VARCHAR ( 50 ) NOT NULL,
 email VARCHAR ( 255 ) UNIQUE NOT NULL,
 created_on TIMESTAMP NOT NULL,
        last_login TIMESTAMP 
);
ERROR:  INVALID_ARGUMENT: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: <UNIQUE> constraint is not supported, create a unique index instead.
psql-test=> CREATE TABLE accounts (
 user_id bigint PRIMARY KEY,
 username VARCHAR ( 50 ) NOT NULL,
 password VARCHAR ( 50 ) NOT NULL,
 email VARCHAR ( 255 )  NOT NULL,
 created_on TIMESTAMP NOT NULL,
        last_login TIMESTAMP 
);
ERROR:  INVALID_ARGUMENT: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Type <timestamp> is not supported.
psql-test=> CREATE TABLE accounts (
 user_id bigint PRIMARY KEY,
 username VARCHAR ( 50 ) NOT NULL,
 password VARCHAR ( 50 ) NOT NULL,
 email VARCHAR ( 255 )  NOT NULL);
CREATE
```
It appears I had to delete UNIQUE,serial,timestamp to create a table in a database of PostgreSQL interface. Is this normal?
