### ISSUE TITLE
Unable to run in docker

### ISSUE THREAD

**Issue by dogmatic69** [GoogleCloudPlatform/pgadapter#405]
Attempted to setup an instance using docker compose but it fails to start.

```
pgadapter_1   | #
pgadapter_1   | # There is insufficient memory for the Java Runtime Environment to continue.
pgadapter_1   | # Cannot create worker GC thread. Out of system resources.
pgadapter_1   | # An error report file with more information is saved as:
pgadapter_1   | # /home/pgadapter/hs_err_pid7.log
```

The relevant docker compose config is:
```
  pgadapter:
    image: gcr.io/cloud-spanner-pg-adapter/pgadapter
    restart: always
    volumes:
      - ./xxx.json:/key.json
    ports:
      - 5433:5432
    command: -p xxx -i xxx -d xxx-c /key.json -x
```

Similar for directly calling docker run:
```
$ docker run -p 5433:5432 -v $(realpath ./xxx.json):/key.json gcr.io/cloud-spanner-pg-adapter/pgadapter -p xxx -i xxx -d xxx -c /key.json -x
java -jar pgadapter.jar -p xxx -i xxx -d xxx -c /key.json -x
[0.026s][warning][os,thread] Failed to start thread "GC Thread#0" - pthread_create failed (EPERM) for attributes: stacksize: 1024k, guardsize: 4k, detached.
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Cannot create worker GC thread. Out of system resources.
# An error report file with more information is saved as:
# /home/pgadapter/hs_err_pid7.log

```
